"""first_migration

Revision ID: 51942809da68
Revises: 
Create Date: 2023-11-07 08:14:18.371751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51942809da68'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wanted',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('sex', sa.Text(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('reward_text', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('images', sa.Text(), nullable=True),
    sa.Column('place_of_birth', sa.Text(), nullable=True),
    sa.Column('warning_message', sa.Text(), nullable=True),
    sa.Column('hair', sa.Text(), nullable=True),
    sa.Column('eyes', sa.Text(), nullable=True),
    sa.Column('race', sa.Text(), nullable=True),
    sa.Column('occupation', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('description'),
    sa.UniqueConstraint('eyes'),
    sa.UniqueConstraint('hair'),
    sa.UniqueConstraint('images'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('occupation'),
    sa.UniqueConstraint('place_of_birth'),
    sa.UniqueConstraint('race'),
    sa.UniqueConstraint('reward_text'),
    sa.UniqueConstraint('sex'),
    sa.UniqueConstraint('warning_message')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wanted')
    # ### end Alembic commands ###
